name: Create Jira Issue

on:
  workflow_dispatch:
    inputs:
      project_key:
        description: "Jira project key"
        required: true
      issue_type:
        description: "Type of the issue (Task, Bug, Story, Sub-task, Epic)"
        required: true
        default: "Task"
        type: choice
        options:
          - "Task"
          - "Bug"
          - "Story"
          - "Sub-task"
          - "Epic"
      parent_issue_key:
        description: "Parent issue key (only for Sub-task)"
        required: false
      assignee:
        description: "Assignee username (optional)"
        required: false
      issue_summary:
        description: "Summary of the issue"
        required: true
      issue_description:
        description: "Description of the issue"
        required: true
      issue_priority:
        description: "Priority of the issue (High, Medium, Low)"
        required: true
        default: "Medium"
        type: choice
        options:
          - "High"
          - "Medium"
          - "Low"
      issue_labels:
        description: "Comma-separated labels for the issue"
        required: false
      attachment_paths:
        description: "Comma-separated paths of attachments"
        required: false

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Jira Issue
        uses: solarekm/jira-action@v1
        with:
          jira_server: ${{ secrets.JIRA_SERVER }}
          jira_username: ${{ secrets.JIRA_USERNAME }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          project_key: ${{ github.event.inputs.project_key }}
          issue_type: ${{ github.event.inputs.issue_type }}
          parent_issue_key: ${{ github.event.inputs.parent_issue_key }}
          assignee: ${{ github.event.inputs.assignee }}
          issue_summary: ${{ github.event.inputs.issue_summary }}
          issue_description: ${{ github.event.inputs.issue_description }}
          issue_priority: ${{ github.event.inputs.issue_priority }}
          issue_labels: ${{ github.event.inputs.issue_labels }}
          attachment_paths: ${{ github.event.inputs.attachment_paths }}
